SELECT [PatientID]
    ,[RowNum]
    ,[OrganisationID]
    ,[ClinicID]
    ,[Gender]    
    ,[Age]
    ,[Ethnicity]
    ,[LAofResidence]
    ,[LSOA]
    ,[GeneralMedicalPractice]
    ,[DateofAttendance]
    ,[InitialContact]
    ,[MainContact]
    ,[FirstContact]
    ,[LocationType] 
    ,[ConsultationMedium]   
    ,[ContraceptiveMethodStatus]
    ,[ContraceptiveMainMethod]
    ,[ContraceptiveOtherMethod1]
    ,[ContraceptiveOtherMethod2]
    ,[ContraceptiveMethodPostCoital1]
    ,[ContraceptiveMethodPostCoital2]
    ,[SRHCareActivity1]
    ,[SRHCareActivity2]
    ,[SRHCareActivity3]
    ,[SRHCareActivity4]
    ,[SRHCareActivity5]
    ,[SRHCareActivity6]
    ,[ReportingYear]
FROM [<Database>].[schema].[<Table>]
WHERE [DateofAttendance] between '<StartDate>' and '<EndDate>'